---
build_from:
  aarch64: homeassistant/aarch64-base-debian:buster
  amd64: homeassistant/amd64-base-debian:buster
  armhf: homeassistant/armhf-base-debian:buster
  armv7: homeassistant/armv7-base-debian:buster
  i386: homeassistant/i386-base-debian:buster
