---
build_from:
  aarch64: homeassistant/aarch64-base-debian:bookworm
  amd64: homeassistant/amd64-base-debian:bookworm
  armhf: homeassistant/armhf-base-debian:bookworm
  armv7: homeassistant/armv7-base-debian:bookworm
  i386: homeassistant/i386-base-debian:bookworm
