---
name: Update Dockerfiles

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '40 16 * * *'
jobs:
  deploy:
    name: Update Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v5

      - name: 📤 Update Dockerfiles
        uses: ludeeus/dockerfile-updater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
